### ISSUE TITLE
Gallery does not include images anymore

### ISSUE THREAD

**Issue by Kuchenmampfer** [nicokaiser/hugo-theme-gallery#127]
When I last built my gallery at April 9th, everything worked fine, but now I get a front page with all my galleries including cover image, but when I open individual galleries, they all have a title and description, but no images. Git diff over the generated `index.html` files tells me that the gallery part just is not there anymore and on compilation, hugo reports that it has processed 25 images despite there being several hundred.
My setup:
- hugo 0.147.5 on arch linux
- this theme installed via `hugo.toml` as advised in the README. But I also tested the git submodule installation which is also broken. So latest version in both cases I guess.
- all images just sit in the directory and are not listed in the front matter
- all images are `webp` (I just read that go is broken with that, but currently, that is the format I use)

Here is an example for a `index.md` that I use:
```
---
description: Botanische Gärten sind großartig, um Pflanzen zu fotografieren. Das wurden bei mir allerdings so viele Fotos, dass ich ihnen hier eine eigene Galerie spendiere.
title: Botanische Gärten
categories: ["Pflanzen"]
params:
  sort_order: desc
  sort_by: Name # Exif.Date
---
```
Did I miss something or is the theme or even hugo itself broken?
