### ISSUE TITLE
Homepage does not display the photo album

### ISSUE THREAD

**Issue by ok-kai** [nicokaiser/hugo-theme-gallery#24]
Hello, author. Thank you for presenting such an attractive theme. Currently, I am encountering a problem where my homepage does not display the photo album, but it is only shown in the categories.

As shown in the picture, the homepage does not have any images.

![image](https://github.com/nicokaiser/hugo-theme-gallery/assets/56720916/acacb2c0-4926-43c5-a42d-14e2ef0d3753)

Images are displayed only in the categories.

![image](https://github.com/nicokaiser/hugo-theme-gallery/assets/56720916/3397a1f6-1317-4984-bd15-0d57edeef2a3)

my configuration file is as follows.

```toml

title = "Keith's Gallery"
languageCode = "en-us"
copyright = "© Keith"
disableKinds = ["taxonomy", "term"]
defaultContentLanguage = "en"
enableRobotsTXT = true
timeZone = "Europe/Berlin"
theme = "gallery"

[params]
  title = "My Gallery"
  description = "Example site for hugo-theme-gallery"
  defaultTheme = "dark"

[author]
  name = "Keith"

[outputs]
  page = ["HTML"]
  home = ["HTML", "RSS"]
  section = ["HTML"]

[imaging]
  resampleFilter = "CatmullRom"
  quality = 75
  [imaging.exif]
    disableDate = false
    disableLatLong = true
    includeFields = "ImageDescription"

[module]
  [module.hugoVersion]
    extended = false
    min = "0.112.0"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "hugo_stats.json"
    target = "assets/watching/hugo_stats.json"

[build]
  writeStats = true
  [[build.cachebusters]]
    source = "assets/watching/hugo_stats\\.json"
    target = "styles\\.css"
  [[build.cachebusters]]
    source = "(postcss|tailwind)\\.config\\.js"
    target = "css"
  [[build.cachebusters]]
    source = "assets/.*\\.(js)"
    target = "js"
  [[build.cachebusters]]
    source = "assets/.*\\.(.*)$"
    target = "$1"

[menu]
[[menu.footer]]
  name = "GitHub"
  url = "https://github.com/nicokaiser/hugo-theme-gallery/"
  weight = 3

```

and directory structure is as follows.

```sh

├─content
│  │  about.md
│  │  imprint.md
│  │  _index.md
│  │
│  ├─animals
│  │  │  _index.md
│  │  │
│  │  ├─cats
│  │  │      dearpan1.jpg
│  │  │      dearpan2.jpg
│  │  │      dearpan3.jpg
│  │  │      feature.jpg
│  │  │      index.md
│  │  │
│  │  └─dogs
│  │          index.md
│  │
│  ├─fashion-beauty
│  │      index.md
│  │
│  ├─nature
│  │      index.md
│  │
│  └─private
│          index.md

```
