### ISSUE TITLE
Create support for Danish language

### ISSUE THREAD

**Issue by JayKayAce** [nicokaiser/hugo-theme-gallery#43]
I propose to add support for danish language bu adding a file in i18n\da.yaml

```
albumCount:
  one: 1 album
  other: "{{ . }} albummer"
albums: albummer
in: i
home: Hjem
pageNotFound: Siden blev ikke fundet
photoCount:
  one: 1 billede
  other: "{{ . }} billeder"
toHomepage: Til forsiden
```
