### ISSUE TITLE
Support resource metadata

### ISSUE THREAD

**Issue by nicokaiser** [nicokaiser/hugo-theme-gallery#46]
Metadata can be set in front matter:

```
resources:
  - src: img_0001.jpg
    title: A nice view in the mountains
    params:
      cover: true
```

In addition to EXIF, support fetching metadata from there.
